export { default as HeroBanner } from "./HeroBanner"
export { default as ClientLogoSection } from "./ClientLogoSection"
export { default as ClientProofSection } from "./ClientProofSection"
export { default as ClientLogoWall } from "./ClientLogoWall"
export { default as ComparisonTabsSection } from "./ComparisonTabsSection"
export { default as MethodologySection } from "./MethodologySection"
export { default as TestimonialsGrid } from "./TestimonialsGrid"
export { default as CalendlySection } from "./CalendlySection"
export { default as FaqAccordion } from "./FaqAccordion"
export { default as DiscoverCtaSection } from "./DiscoverCtaSection"
export { default as JoinStatsSection } from "./JoinStatsSection"
export { default as SecurityBadgeSection } from "./SecurityBadgeSection"
export { default as CapabilitiesGrid } from "./CapabilitiesGrid"
export { default as ServicesCardsGrid } from "./ServicesCardsGrid"
export { default as FeatureNumberList } from "./FeatureNumberList"
export { default as SolutionCardsSection } from "./SolutionCardsSection"
export { default as CaseStudyCardsSection } from "./CaseStudyCardsSection"
export { default as IndustryTabsSection } from "./IndustryTabsSection"
export { default as TestimonialCtaBanner } from "./TestimonialCtaBanner"
export { default as AuditCtaBanner } from "./AuditCtaBanner"
export { default as RemoteTeamSection } from "./RemoteTeamSection"
export { default as ApplicationFormSection } from "./ApplicationFormSection"
export { default as TextContentSection } from "./TextContentSection"
export { default as PartnerEcosystemSection } from "./PartnerEcosystemSection"
export { default as IndustryCaseStudy } from "./IndustryCaseStudy"
export { default as ServicesWorkflowTabs } from "./ServicesWorkflowTabs"

/* Long-form industry content sections — copy in src/data/industrySections.ts */
export { default as CapabilityBlocksSection } from "./CapabilityBlocksSection"
export { default as BenefitLedgerSection } from "./BenefitLedgerSection"
export { default as TemplateSpecSection } from "./TemplateSpecSection"
export { default as RichText } from "./RichText"

/* CRO kit (PDF action items) */
export { default as TrustBadgeRow } from "./TrustBadgeRow"
/* The bar renders once in <SiteFrame>; pages set their copy via this. */
export { default as StickyCtaConfig } from "./StickyCtaContext"
export type { StickyCtaValue } from "./StickyCtaContext"
export { default as DualCtaRow } from "./DualCtaRow"
export { default as BeforeAfterSection } from "./BeforeAfterSection"
export { default as StatMetricBanner } from "./StatMetricBanner"
export { default as MicroCaseStudyBox } from "./MicroCaseStudyBox"
export { default as SymptomsChecklist } from "./SymptomsChecklist"
export { default as RoiCalculator } from "./RoiCalculator"
export { default as LeadForm } from "./LeadForm"
export { default as CroSections } from "./CroSections"
export type { CroSectionsData } from "./CroSections"
export { default as TestimonialFilterGrid } from "./TestimonialFilterGrid"
export { default as WorkflowConnector } from "./WorkflowConnector"
export { default as SolutionSelector } from "./SolutionSelector"
export { default as TrainingRecommender } from "./TrainingRecommender"
export { default as EcosystemGrid } from "./EcosystemGrid"

/* Messaging-channel integration pages (/integrations/whatsapp | line | viber) */
export { default as ChannelStackMatrix } from "./ChannelStackMatrix"
export { default as ChannelSpecPanel } from "./ChannelSpecPanel"

export type * from "./types"
